const Logger = require('../dist/index').Logger;

const oLogger1 = new Logger({service: 'Test', syslog: true});
oLogger1.d('Debug', {test: 'Debugging'});
let oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});

oLogger1.d('Debug', {test: 'Debugging'});
oLogger1.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});
oLogger2 = new Logger({service: '2', syslog: true});
oLogger2.d('Debug', {test: 'Debugging'});